from __future__ import annotations
import io
from uuid import UUID

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.models import Candidate, DiversityReport, JobDescription


async def generate_candidate_pdf(db: AsyncSession, candidate_id: UUID) -> bytes:
    result = await db.execute(
        select(Candidate)
        .where(Candidate.id == candidate_id)
        .options(
            selectinload(Candidate.scores),
            selectinload(Candidate.interview_questions),
            selectinload(Candidate.skills),
            selectinload(Candidate.job_description),
        )
    )
    candidate = result.scalar_one_or_none()
    if not candidate:
        raise ValueError("Candidate not found")

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=0.75 * inch, bottomMargin=0.75 * inch)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("Title", parent=styles["Heading1"], textColor=colors.HexColor("#2563EB"), spaceAfter=12)
    heading_style = ParagraphStyle("Heading", parent=styles["Heading2"], textColor=colors.HexColor("#0F172A"), spaceAfter=8)
    body_style = styles["Normal"]

    story = []
    story.append(Paragraph("RecruitIQ AI — Candidate Report", title_style))
    story.append(Paragraph(f"<b>{candidate.name}</b>", heading_style))
    story.append(Spacer(1, 12))

    if candidate.scores:
        score_data = [
            ["Metric", "Score"],
            ["Overall", f"{candidate.scores.overall_score:.1f}"],
            ["Skills", f"{candidate.scores.skill_score:.1f}"],
            ["Experience", f"{candidate.scores.experience_score:.1f}"],
            ["Domain", f"{candidate.scores.domain_score:.1f}"],
            ["Education", f"{candidate.scores.education_score:.1f}"],
            ["Soft Skills", f"{candidate.scores.soft_skill_score:.1f}"],
        ]
        table = Table(score_data, colWidths=[2.5 * inch, 1.5 * inch])
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2563EB")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
        ]))
        story.append(Paragraph("Score Breakdown", heading_style))
        story.append(table)
        story.append(Spacer(1, 16))

        if candidate.scores.executive_summary:
            story.append(Paragraph("Executive Summary", heading_style))
            story.append(Paragraph(candidate.scores.executive_summary, body_style))
            story.append(Spacer(1, 12))

        explanation = candidate.scores.explanation or {}
        for section, key in [("Strengths", "strengths"), ("Gaps", "gaps"), ("Risks", "risks"), ("Potential", "potential")]:
            items = explanation.get(key, [])
            if items:
                story.append(Paragraph(section, heading_style))
                for item in items:
                    story.append(Paragraph(f"• {item}", body_style))
                story.append(Spacer(1, 8))

    if candidate.interview_questions:
        story.append(Paragraph("Interview Questions", heading_style))
        for q in candidate.interview_questions:
            story.append(Paragraph(f"<b>[{q.category}]</b> {q.question}", body_style))
            story.append(Spacer(1, 6))

    if candidate.job_description_id:
        div_result = await db.execute(
            select(DiversityReport)
            .where(DiversityReport.job_description_id == candidate.job_description_id)
            .order_by(DiversityReport.created_at.desc())
            .limit(1)
        )
        div_report = div_result.scalar_one_or_none()
        if div_report and div_report.alerts:
            story.append(Paragraph("Diversity Insights", heading_style))
            for alert in div_report.alerts[:3]:
                story.append(Paragraph(f"⚠ {alert.get('message', '')}", body_style))

    story.append(Spacer(1, 24))
    story.append(Paragraph("<i>Generated by RecruitIQ AI</i>", body_style))

    doc.build(story)
    return buffer.getvalue()


async def generate_pool_pdf(db: AsyncSession, job_description_id: UUID | None = None) -> bytes:
    query = select(Candidate).options(selectinload(Candidate.scores), selectinload(Candidate.skills))
    if job_description_id:
        query = query.where(Candidate.job_description_id == job_description_id)
    result = await db.execute(query)
    candidates = sorted(list(result.scalars().all()), key=lambda c: c.rank or 9999)

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=0.75 * inch, bottomMargin=0.75 * inch)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "Title", parent=styles["Heading1"], textColor=colors.HexColor("#2563EB"), spaceAfter=12
    )
    heading_style = ParagraphStyle(
        "Heading", parent=styles["Heading2"], textColor=colors.HexColor("#0F172A"), spaceAfter=8
    )

    story = [Paragraph("RecruitIQ AI — Candidate Ranking Report", title_style)]
    if job_description_id:
        jd = await db.get(JobDescription, job_description_id)
        if jd:
            story.append(Paragraph(f"Role: <b>{jd.title}</b>", styles["Normal"]))
    story.append(Spacer(1, 16))

    table_data = [["Rank", "Name", "Score", "Experience", "Top Skills", "Status"]]
    for c in candidates:
        table_data.append([
            str(c.rank or "-"),
            c.name,
            f"{c.scores.overall_score:.1f}" if c.scores else "—",
            f"{c.years_of_experience:.0f}y",
            ", ".join(s.skill_name for s in c.skills[:4]),
            c.status,
        ])

    table = Table(table_data, colWidths=[0.6 * inch, 1.4 * inch, 0.7 * inch, 0.9 * inch, 2.2 * inch, 0.8 * inch])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2563EB")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
    ]))
    story.append(Paragraph("Ranked Candidates", heading_style))
    story.append(table)
    story.append(Spacer(1, 24))
    story.append(Paragraph("<i>Generated by RecruitIQ AI</i>", styles["Normal"]))

    doc.build(story)
    return buffer.getvalue()
